//REQUIRE STANDARD CODE LIBRARIES: this is the standard js file generated by express generator: app.js, this holds all the routes
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

//REQUIRE ROUTING GET REQUEST ADDRESSES: (1) add a new variable with assigned route here for each page address that will be sent as a web request to render
var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var addBreedRouter = require('./routes/addBreed');
var addCatRouter = require('./routes/addCat');

//initialize the express library you required at the top - middleware below runs on top of express (which is my variable app.)
var app = express();

//REQUIRE TEMPLATING ENGINE: view engine setup (hbs is handlebars, views is the default directory), runs on top of express
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'hbs');

//MIDDLEWARE: app.use is various middleware that intercepts http requests and does stuff...
app.use(logger('dev'));
//this replaces body-parser, which is now built into express, we call it by using .json()
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

//STATIC FILES: this tells Express where your public static files will live, ie images, pdf's, etc. (no need to include 'public' in the image routes, express knows when you designate it here)
app.use(express.static(path.join(__dirname, 'public')));

//ROUTING(2) add a corresponding .use for each new page route you create
app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/cats/add-breed', addBreedRouter);
app.use('/cats/add-cat', addCatRouter);

// catch any 404s and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
